### ISSUE TITLE
/get

### ISSUE THREAD

**Issue by stepinbefore** [Woppilif/VkTMessenger-PHP-Telegram-bot#1]
delete

**Comment by Woppilif** [comment]
Можно чуть подробнее?
Как минимум, после ввода команды должна быть какая-либо ошибка и т.д

**Comment by stepinbefore** [comment]
Нет ошибки не присылает, просто ноль реакций при вводе команды /get

**Comment by Woppilif** [comment]
Сколько раз вводили ее и какие данные указали при регистрации?

**Comment by stepinbefore** [comment]
Пробывал и один раз. И после переустановки пару раз. Ну все что запрашивал бот, токен ид приложения свой ид. Кстати предыдущая версия работает без проблем.

**Comment by Woppilif** [comment]
Напишите пожалуйста свой ВК id или имя в Telegram. 
Нужно для проверки данных в базе.

**Comment by stepinbefore** [comment]
Telegram @stepinbefore

**Comment by Woppilif** [comment]
Окей, теперь нужен ВК id.

**Comment by stepinbefore** [comment]
id305097471

**Comment by Woppilif** [comment]
Вы не были найдены в базе данных согласно вашему vk id.
В ближайшее время выйдет масштабное обновление. Новости тут: https://vk.com/vktmessenger
Так же вы можете писать нам в личные сообщения для ускорения процесса.

**Comment by stepinbefore** [comment]
Вы не поняли меня, я же на свой сервер установил, как я окажусь в Вашей базе данных?

**Comment by Woppilif** [comment]
Вот оно что.
В таком случае лучше всего посмотреть логи.
У меня на продакшене работает.

**Comment by stepinbefore** [comment]
да, сначала ругался на версию php, но теперь логов нет, но по прежнему бот молчит:(

**Comment by stepinbefore** [comment]
PHP Fatal error:  Call to undefined method VKMessages::returnUsername() in /var/www/*******/data/www/******/engine/controllers/vk.php on line 65
